### ISSUE TITLE
Issues when depositing TONI-PLS LP Tokens to metamask for Staking.

### ISSUE THREAD

**Issue by Arctic-Crypto-Viking** [Daytona-Finance/Contracts#1]
Status on Metamask is transaction decoding is not available for chainId 369 and Metamask says it cannot calcluate Gas fees, one can proceed but there are some bugs here.

----
We were not able to estimate gas. There might be an error in the contract and this transaction may fail.
Raw data: 
0xe2bbb158000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000092c29efa9eb4a5289ff

Just says Pending on the process in Metamask..
Attached screenshot from error.

Also, here is the link to the contract address that comes from daytona to the metamask:
0xAc6fBc06C8c0477ba8fc117adb52881c1Cc580dA

https://scan.pulsechain.com/address/0xAc6fBc06C8c0477ba8fc117adb52881c1Cc580dA/transactions#address

**Comment by smoo7h** [comment]
Metamask issue

**Comment by Arctic-Crypto-Viking** [comment]
👍

tor. 16. nov. 2023 kl. 09:29 skrev smoo7h ***@***.***>:
